version: '3.6'

services:
  mongodb:
    image: mongo:5.0.2
    container_name: siege-mongodb
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./mongodb/mongo-volume:/data/db

  application:
    container_name: siege-application
    depends_on:
      - mongodb
    build: ./nodejs
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    hostname: siege-application
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/api/health/check"]
        interval: 5s
        timeout: 5s
        retries: 5

  siege-c10:
    container_name: siege-c10
    image: jstarcher/siege
    volumes:
      - ./siege/urls.txt:/opt/urls.txt
    depends_on:
      application:
        condition: service_healthy
    command: -c10 -r5 -f /opt/urls.txt

  siege-c25:
    container_name: siege-c25
    image: jstarcher/siege
    volumes:
      - ./siege/urls.txt:/opt/urls.txt
    depends_on:
      application:
        condition: service_healthy
    command: -c25 -r5 -f /opt/urls.txt

  siege-c50:
    container_name: siege-c50
    image: jstarcher/siege
    volumes:
      - ./siege/urls.txt:/opt/urls.txt
    depends_on:
      application:
        condition: service_healthy
    command: -c50 -r5 -f /opt/urls.txt

  siege-c100:
    container_name: siege-c100
    image: jstarcher/siege
    volumes:
      - ./siege/urls.txt:/opt/urls.txt
    depends_on:
      application:
        condition: service_healthy
    command: -c100 -r5 -f /opt/urls.txt